<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="2" ignored="0" total="8" passed="6">
  <reporter-output>
  </reporter-output>
  <suite name="POC Tests - Contacts Manager" duration-ms="224468" started-at="2020-07-02T14:42:25 IST" finished-at="2020-07-02T14:46:09 IST">
    <groups>
    </groups>
    <test name="Contacts HomePage Test" duration-ms="117779" started-at="2020-07-02T14:42:25 IST" finished-at="2020-07-02T14:44:22 IST">
      <class name="com.qa.contacts.tests.ContactsHomePageTest">
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.qa.contacts.tests.ContactsHomePageTest@695a69a1]" name="setUp" is-config="true" duration-ms="25846" started-at="2020-07-02T14:42:25 IST" finished-at="2020-07-02T14:42:50 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="verifyContactHeaderTest()[pri:1, instance:com.qa.contacts.tests.ContactsHomePageTest@695a69a1]" name="verifyContactHeaderTest" duration-ms="201" started-at="2020-07-02T14:42:51 IST" description="verify contact header test.....!!!" finished-at="2020-07-02T14:42:51 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyContactHeaderTest -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.qa.contacts.tests.ContactsHomePageTest@695a69a1]" name="tearDown" is-config="true" duration-ms="296" started-at="2020-07-02T14:42:51 IST" finished-at="2020-07-02T14:42:51 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.qa.contacts.tests.ContactsHomePageTest@695a69a1]" name="setUp" is-config="true" duration-ms="24689" started-at="2020-07-02T14:42:51 IST" finished-at="2020-07-02T14:43:16 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="verifySetPasswordTest()[pri:2, instance:com.qa.contacts.tests.ContactsHomePageTest@695a69a1]" name="verifySetPasswordTest" duration-ms="20123" started-at="2020-07-02T14:43:16 IST" finished-at="2020-07-02T14:43:36 IST">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.failNotEquals(Assert.java:968)
at org.testng.Assert.assertTrue(Assert.java:43)
at org.testng.Assert.assertTrue(Assert.java:53)
at com.qa.contacts.tests.ContactsHomePageTest.verifySetPasswordTest(ContactsHomePageTest.java:33)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:821)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:767)
at org.testng.TestRunner.run(TestRunner.java:588)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1214)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1136)
at org.testng.TestNG.runSuites(TestNG.java:1066)
at org.testng.TestNG.run(TestNG.java:1034)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifySetPasswordTest -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.qa.contacts.tests.ContactsHomePageTest@695a69a1]" name="tearDown" is-config="true" duration-ms="191" started-at="2020-07-02T14:43:37 IST" finished-at="2020-07-02T14:43:37 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.qa.contacts.tests.ContactsHomePageTest@695a69a1]" name="setUp" is-config="true" duration-ms="22378" started-at="2020-07-02T14:43:37 IST" finished-at="2020-07-02T14:43:59 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="goToBackUpRestoreTest()[pri:3, instance:com.qa.contacts.tests.ContactsHomePageTest@695a69a1]" name="goToBackUpRestoreTest" duration-ms="366" started-at="2020-07-02T14:43:59 IST" finished-at="2020-07-02T14:44:00 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- goToBackUpRestoreTest -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.qa.contacts.tests.ContactsHomePageTest@695a69a1]" name="tearDown" is-config="true" duration-ms="303" started-at="2020-07-02T14:44:00 IST" finished-at="2020-07-02T14:44:00 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.qa.contacts.tests.ContactsHomePageTest@695a69a1]" name="setUp" is-config="true" duration-ms="21674" started-at="2020-07-02T14:44:00 IST" finished-at="2020-07-02T14:44:22 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="goToContactUsTest()[pri:4, instance:com.qa.contacts.tests.ContactsHomePageTest@695a69a1]" name="goToContactUsTest" duration-ms="362" started-at="2020-07-02T14:44:22 IST" finished-at="2020-07-02T14:44:22 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- goToContactUsTest -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.qa.contacts.tests.ContactsHomePageTest@695a69a1]" name="tearDown" is-config="true" duration-ms="264" started-at="2020-07-02T14:44:22 IST" finished-at="2020-07-02T14:44:22 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.qa.contacts.tests.ContactsHomePageTest -->
    </test> <!-- Contacts HomePage Test -->
    <test name="BackupRestore Test" duration-ms="49859" started-at="2020-07-02T14:44:22 IST" finished-at="2020-07-02T14:45:12 IST">
      <class name="com.qa.contacts.tests.BackupRestoreTest">
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.qa.contacts.tests.BackupRestoreTest@5226e402]" name="setUp" is-config="true" duration-ms="21702" started-at="2020-07-02T14:44:22 IST" finished-at="2020-07-02T14:44:44 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="verifyRestoreContactsTextTest()[pri:1, instance:com.qa.contacts.tests.BackupRestoreTest@5226e402]" name="verifyRestoreContactsTextTest" duration-ms="1588" started-at="2020-07-02T14:44:44 IST" description="verify restore contact text.....!!!" finished-at="2020-07-02T14:44:46 IST">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Restore Contats] but found [Restore Contacts]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Restore Contats] but found [Restore Contacts]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:575)
at org.testng.Assert.assertEquals(Assert.java:585)
at com.qa.contacts.tests.BackupRestoreTest.verifyRestoreContactsTextTest(BackupRestoreTest.java:35)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:821)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:767)
at org.testng.TestRunner.run(TestRunner.java:588)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1214)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1136)
at org.testng.TestNG.runSuites(TestNG.java:1066)
at org.testng.TestNG.run(TestNG.java:1034)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyRestoreContactsTextTest -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.qa.contacts.tests.BackupRestoreTest@5226e402]" name="tearDown" is-config="true" duration-ms="238" started-at="2020-07-02T14:44:46 IST" finished-at="2020-07-02T14:44:47 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.qa.contacts.tests.BackupRestoreTest@5226e402]" name="setUp" is-config="true" duration-ms="23592" started-at="2020-07-02T14:44:47 IST" finished-at="2020-07-02T14:45:10 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="verifyContactClickTest()[pri:2, instance:com.qa.contacts.tests.BackupRestoreTest@5226e402]" name="verifyContactClickTest" duration-ms="1762" started-at="2020-07-02T14:45:10 IST" description="verify clicking on BackupRestore test.....!!!" finished-at="2020-07-02T14:45:12 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyContactClickTest -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.qa.contacts.tests.BackupRestoreTest@5226e402]" name="tearDown" is-config="true" duration-ms="324" started-at="2020-07-02T14:45:12 IST" finished-at="2020-07-02T14:45:12 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.qa.contacts.tests.BackupRestoreTest -->
    </test> <!-- BackupRestore Test -->
    <test name="New Contact Us Request Test" duration-ms="56775" started-at="2020-07-02T14:45:12 IST" finished-at="2020-07-02T14:46:09 IST">
      <class name="com.qa.contacts.tests.ContactusTest">
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.qa.contacts.tests.ContactusTest@6a4d7f76]" name="setUp" is-config="true" duration-ms="22544" started-at="2020-07-02T14:45:12 IST" finished-at="2020-07-02T14:45:35 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="verifyContactUsHeaderTest()[pri:1, instance:com.qa.contacts.tests.ContactusTest@6a4d7f76]" name="verifyContactUsHeaderTest" duration-ms="1867" started-at="2020-07-02T14:45:35 IST" description="verify contactus header test.....!!!" finished-at="2020-07-02T14:45:37 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyContactUsHeaderTest -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.qa.contacts.tests.ContactusTest@6a4d7f76]" name="tearDown" is-config="true" duration-ms="320" started-at="2020-07-02T14:45:37 IST" finished-at="2020-07-02T14:45:37 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.qa.contacts.tests.ContactusTest@6a4d7f76]" name="setUp" is-config="true" duration-ms="24401" started-at="2020-07-02T14:45:38 IST" finished-at="2020-07-02T14:46:03 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="newContactUsRequestTest(java.lang.String, java.lang.String, java.lang.String)[pri:2, instance:com.qa.contacts.tests.ContactusTest@6a4d7f76]" name="newContactUsRequestTest" duration-ms="5651" started-at="2020-07-02T14:46:03 IST" description="Verify adding new contact us request" data-provider="getContactusData" finished-at="2020-07-02T14:46:09 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[Sagar]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[8925611111]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[test@test.com]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- newContactUsRequestTest -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.qa.contacts.tests.ContactusTest@6a4d7f76]" name="tearDown" is-config="true" duration-ms="454" started-at="2020-07-02T14:46:09 IST" finished-at="2020-07-02T14:46:09 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.qa.contacts.tests.ContactusTest -->
    </test> <!-- New Contact Us Request Test -->
  </suite> <!-- POC Tests - Contacts Manager -->
</testng-results>
